es_host: 127.0.0.1
es_port: 9200
name: CONFIG.YAML RULEZ
type: frequency
index: cowrie-*
num_events: 1
timeframe:
  minutes: 4
filter:
  - term:
      eventid : "cowrie.session.connect"

run_every:
  seconds: 20
buffer_time:
  minutes: 1
writeback_index:
  "elastalert_match"
rules_folder: .


alert:
  - "command"
command: ["/home/ubuntu/connect.sh", "{src_ip}"]